discussions/discussions/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('threads/', include('threads.urls')),
]

discussions/threads/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name='threads'
urlpatterns = [
	path('',
		views.PostsView.as_view(), name='all_posts'),
	path('posts/new',
		views.PostCreate.as_view(), name='new_post'),

	path('reactions',
		views.ReactListView.as_view(), name='reactions'),
	path('reaction/<int:pk>',
		views.ReactDetailView.as_view(), name='reaction_detail'),
	path('reaction/create',
		views.ReactCreateView.as_view(), name='reaction_create'),
	path('reaction/<int:pk>/resp',
        views.RespCreateView.as_view(), name='reaction_resp_create'),

	path('brainstorms',
		views.BrainListView.as_view(), name='brainstorms'),
	path('brainstorm/<int:pk>',
		views.BrainDetailView.as_view(), name='brainstorm_detail'),

	path('brainstorm/<int:pk>/addupvote', 
		views.AddUpvoteView.as_view(), name='brainstorm_add_upvote'),

	path('brainstorm/create',
		views.BrainCreateView.as_view(), name='brainstorm_create'),
	path('brainstorm/<int:pk>/resp',
		views.BrainRespCreateView.as_view(), name='brainstorm_resp_create'),
	path('brainstorm/<int:pk>/comment',
		views.BrainCommentCreateView.as_view(), name='brainstorm_comment_create'),

	path('discussions',
		views.DiscListView.as_view(), name='discussions'),
	path('discussion/<int:pk>',
		views.DiscDetailView.as_view(), name='discussion_detail'),
	path('discussion/create',
		views.DiscCreateView.as_view(), name='discussion_create'),
	path('discussion/<int:pk>/reply',
        views.ReplyCreateView.as_view(), name='discussion_reply_create'),
]

discussions/threads/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.utils import timezone
from datetime import datetime

# Create your models here.
class Reaction(models.Model):
	topic = models.TextField(default='General')
	text = text = models.TextField()
	owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	created_at = models.DateTimeField(default=timezone.now)

	responses = models.ManyToManyField(settings.AUTH_USER_MODEL, through='Response', related_name='thread_responses')

	def __str__(self):
		return self.topic

class Response(models.Model):
	text = text = models.TextField()
	owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	created_at = models.DateTimeField(default=timezone.now)
	reaction = models.ForeignKey(Reaction, on_delete=models.CASCADE)

	def __str__(self):
		return self.text

# ----------------------------------------------------------------------------

class Brainstorm(models.Model):
	topic = models.TextField(default='General')
	text = text = models.TextField()
	owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	created_at = models.DateTimeField(default=timezone.now)

	brainstormresponses = models.ManyToManyField(settings.AUTH_USER_MODEL, through='BrainstormResponse', related_name='thread_brainstormresponses')

	def __str__(self):
		return self.topic

class BrainstormResponse(models.Model):
	text = models.TextField()
	owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	created_at = models.DateTimeField(default=timezone.now)

	brainstorm = models.ForeignKey(Brainstorm, on_delete=models.CASCADE)
	# https://books.agiliq.com/projects/django-orm-cookbook/en/latest/self_fk.html
	#parent = models.ForeignKey("self", on_delete=models.CASCADE) # making this optional
	#level = 1

	votes = models.ManyToManyField(settings.AUTH_USER_MODEL, through='Vote', related_name='thread_brainstormresponsevotes')
	comments = models.ManyToManyField(settings.AUTH_USER_MODEL, through='BrainstormComment', related_name='thread_brainstormresponsecomments')

	def __str__(self):
		return self.text

class BrainstormComment(models.Model): # ask Chuck?
	text = models.TextField()
	owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	created_at = models.DateTimeField(default=timezone.now)

	brainstormresponse = models.ForeignKey(BrainstormResponse, on_delete=models.CASCADE)
	#parent = models.ForeignKey(BrainstormResponse, on_delete=models.CASCADE)

	def __str__(self):
		return self.text

class Vote(models.Model):
	owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	brainresponse = models.ForeignKey(BrainstormResponse, on_delete=models.CASCADE)
	#direction = mdoels.IntegerField(default=1)
	vote_choices = [('u','UP'), ('d','DOWN')]
	direction = models.CharField(max_length=1, choices=vote_choices, default=vote_choices[0][0])

	def __str__(self):
		return self.brainresponse.text

# ----------------------------------------------------------------------------

class Discussion(models.Model):
	topic = models.TextField(default='General')
	text = models.TextField(default='What do you think?')
	owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	created_at = models.DateTimeField(default=timezone.now)

	replies = models.ManyToManyField(settings.AUTH_USER_MODEL, through='DiscussionReply', related_name='thread_replies')
	viewed = models.ManyToManyField(settings.AUTH_USER_MODEL, through='ViewedDiscussion', related_name='thread_vieweddiscussions')


	def __str__(self):
		return self.topic

class DiscussionReply(models.Model):
	text = models.TextField()
	owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	created_at = models.DateTimeField(default=timezone.now)

	discussion = models.ForeignKey(Discussion, on_delete=models.CASCADE)
	

	def __str__(self):
		return self.text

class ViewedDiscussion(models.Model):
	owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	discussion = models.ForeignKey(Discussion, on_delete=models.CASCADE)
	last_seen = models.IntegerField(default=0)

discussions/threads/forms.py
from django import forms

from django.urls import reverse
from crispy_forms.helper import FormHelper

from threads.models import Reaction, Response, Brainstorm, BrainstormResponse, BrainstormComment, Discussion, DiscussionReply

class ReactForm(forms.ModelForm):
	class Meta:
		model = Reaction
		fields = ['topic','text']

class ResponseForm(forms.ModelForm):
	class Meta:
		model = Response
		fields = ['text']
	#resp = forms.CharField(required=True, max_length=500, min_length=3, strip=True)
	#owner = User

#-----------------------------------------------------------------------------

class BrainForm(forms.ModelForm):
	class Meta:
		model = Brainstorm
		fields = ['topic', 'text']  # Picture is manual

class BrainResponseForm(forms.ModelForm):
	class Meta:
		model = BrainstormResponse
		fields = ['text']

class BrainCommentForm(forms.ModelForm):
	class Meta: 
		model = BrainstormComment
		fields = ['text']

#-----------------------------------------------------------------------------

class DiscForm(forms.ModelForm):
	class Meta:
		model = Discussion
		fields = ['topic','text']

class ReplyForm(forms.ModelForm):
	class Meta:
		model = Discussion
		fields = ['text']
	# def __init__(self, *args, **kwargs):
	# 	super().__init__(*args, **kwargs)
	# 	self.helper = FormHelper()
	# 	form.helper.form_action = reverse('threads:reaction_detail', kwargs={'react_id': react.id})

discussions/threads/views.py
from django.shortcuts import render
from threads.models import Reaction, Response, Brainstorm, BrainstormResponse, BrainstormComment, Vote, Discussion, DiscussionReply, ViewedDiscussion
from django.contrib.auth.models import User
from django.views import View
from django.views.generic import CreateView, UpdateView, DeleteView, ListView, DetailView
from django.urls import reverse_lazy, reverse
from django.shortcuts import render, redirect, get_object_or_404
from threads.forms import ResponseForm, BrainForm, BrainResponseForm, BrainCommentForm, ReplyForm, ReactForm, DiscForm
from django.contrib.auth.mixins import LoginRequiredMixin


# dj4e-samples/favsql/sqldebug.py
from django.db import connection
def print_queries():
    retval = list()
    for i, query in enumerate(connection.queries):
        q = query['sql']
        if q.find('SELECT "django_session"."session_key"') == 0 : continue
        if q.find('SELECT "auth_user"."id", "auth_user"."password"') == 0 : continue
        print(q)

# logging stuff ------------------------------------------------------------------------
import logging

logging.config.dictConfig({
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'console': {
            'format': '%(name)-12s %(levelname)-8s %(message)s'
        },
        'file': {
            'format': '%(asctime)s %(name)-12s %(levelname)-8s %(message)s'
        }
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'console'
        },
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'formatter': 'file',
            'filename': 'debug.log'
        }
    },
    'loggers': {
        '': {
            'level': 'DEBUG',
            'handlers': ['console', 'file']
        },
        'django.db.backends': {
            'level': 'DEBUG',
            'handlers': ['console', 'file']
        }
    }
})

logger = logging.getLogger(__name__)

# ------------------------------------------------------------------------------------
import operator

class PostsView(ListView):
	template_name = "threads/all_posts.html"

	def get(self, request) :
		all_posts = []
		models = {Reaction:('reaction', 'lightseagreen'), 
				  Brainstorm:('brainstorm','mediumpurple'), 
				  Discussion:('discussion','lightcoral')}
		for model in models:
			posts = model.objects.all()
			for p in posts:
				p.type = models[model][0]
				p.color = models[model][1]
			all_posts.extend(posts)

		all_posts = sorted(all_posts, key=operator.attrgetter('created_at'))
		#all_posts.append(Reaction.objects.all())
		#model = Brainstorm
		#all_posts.append(Brainstorm.objects.all())
		#model = Discussion
		#all_posts.append(Discussion.objects.all())
		print(all_posts)
		ctx = {'all_posts':all_posts}
		print_queries()
		return render(request, self.template_name, ctx)

class PostCreate(View):
	template_name = "threads/new_post.html"
	def get(self, request) :
		return render(request, self.template_name)


# ------------------------------------------------------------------------------------

class ReactListView(ListView):
	model = Reaction
	template_name = "threads/thread_list.html"

	def get(self, request) :
		r_list = Reaction.objects.all()
		ctx = {'r_list':r_list}
		#print(r_list[0])
		print_queries()
		return render(request, self.template_name, ctx)

class ReactDetailView(DetailView):
	model = Reaction
	template_name = "threads/thread_detail.html"

	def get(self, request, pk) :
		react = Reaction.objects.get(id=pk)
		resps = Response.objects.filter(reaction=react)
		resp_form = ResponseForm()
		posted_yet = 0
		for r in resps:
			if self.request.user == r.owner:
				posted_yet = 1
			elif self.request.user == react.owner:
				posted_yet = 1
		ctx = {'react':react, 'resps':resps, 'resp_form':resp_form, 'posted_yet':posted_yet}
		print_queries()
		return render(request, self.template_name, ctx)

# class ReactCreateView(LoginRequiredMixin, CreateView):
# #class ReactCreateView(CreateView):
# 	model = Reaction
# 	template_name = "threads/thread_form.html"
# 	fields = ['topic', 'text']
# 	success_url = reverse_lazy('threads:all_posts')
# 	print_queries()

class ReactCreateView(LoginRequiredMixin, CreateView):
	template_name = "threads/thread_form.html"
	success_url = reverse_lazy('threads:all_posts')

	def get(self, request, pk=None):
		form = ReactForm()
		ctx = {'form': form}
		return render(request, self.template_name, ctx)

	def post(self, request, pk=None):
		form = ReactForm(request.POST) 
		react = form.save(commit=False)
		react.owner = self.request.user
		react.save()
		print_queries()
		return redirect(self.success_url)

# class ReactCreateView(View):
# 	def get(self, request):
# 		model = Reaction
# 		template_name = "threads/thread_form.html"
# 		fields = ['topic', 'text', 'owner']
# 		success_url = reverse_lazy('threads:all_posts')
# 		form = ReactForm
# 		ctx = {'form':form}
# 		return render(request, template_name, ctx)

# 	def post(self, request, pk) :
# 		owner = get_object_or_404(User, id=request.POST['owner'])
# 		react = Reaction(topic=request.POST['topic'], text=request.POST['text'], owner=owner)
# 		react.save()
# 		return redirect(reverse('threads:reaction_detail', args=[pk.id]))


	# def get(self, request):
	# 	model = Reaction
	# 	template_name = "threads/thread_form.html"
	# 	fields = ['topic', 'text', 'owner']
		#success_url = reverse_lazy('threads:all_posts')
		#return redirect(reverse('threads:reaction_detail', args=[1]))
		#return redirect(reverse('threads:all_posts'))

class RespCreateView(View):
	model = Response
	def post(self, request, pk) :
		r = get_object_or_404(Reaction, id=pk)
		owner = self.request.user
		resp = Response(text=request.POST['text'], owner=owner, reaction=r)
		resp.save()
		print_queries()
		return redirect(reverse('threads:reaction_detail', args=[pk]))

# ------------------------------------------------------------------------------------

class BrainListView(ListView):
	model = Brainstorm
	template_name = 'threads/brain_list.html'

	def get(self, request) :
		b_list = Brainstorm.objects.all()
		ctx = {'b_list':b_list}
		#print(b_list[0])
		print_queries()
		return render(request, self.template_name, ctx)

class BrainDetailView(DetailView):
	model = BrainstormResponse
	template_name = "threads/brain_detail.html"

	def get(self, request, pk) :
		brain = Brainstorm.objects.get(id=pk)
		brain_resps = BrainstormResponse.objects.filter(brainstorm=brain)
		#brain.votes = []
		#brain.comments = []
		brain.resps = []
		for resp in brain_resps:
			r = resp
			# vote totals
			r.r_votes = Vote.objects.filter(brainresponse=resp)
			r.up_votes = Vote.objects.filter(brainresponse=resp, direction='u')
			r.down_votes = Vote.objects.filter(brainresponse=resp, direction='d')

			# user voted ?
			x = r.r_votes.filter(owner=self.request.user)
			if len(x) > 0:
				r.voted = 'yep'
				r.voted_dir = x.first().direction
			else:
				r.voted = 'nope'
				#r.voted_dir = 'nope'

			r.r_comments = BrainstormComment.objects.filter(brainstormresponse=resp)
			r.up = len(r.up_votes)
			r.down = len(r.down_votes)
			r.net = r.up - r.down
			r.num_votes = len(r.r_votes)
			brain.resps.append(r)
		brain.resps = sorted(brain.resps, key=operator.attrgetter('net'), reverse=True)
		#brain.resps_leastvotes = sorted(brain.resps, key=operator.attrgetter('net'))
		#brain.resps_newest = sorted(brain.resps, key=operator.attrgetter('created_at'))
		#brain.resps_oldest = sorted(brain.resps, key=operator.attrgetter('created_at'), reverse=True)

		#brain.num_votes = len(brain.votes)

		resp_form = BrainResponseForm()
		comment_form = BrainCommentForm()
		ctx = {'brain':brain, 'resp_form':resp_form, 'comment_form':comment_form}
		#ctx = {'brain':brain, 'brain_resps':resps, 'resp_form':resp_form}#, 'votes':votes, 'comments':comments}
		print_queries()

		return render(request, self.template_name, ctx)

class BrainCreateView(CreateView):
#class ReactCreateView(CreateView):
	#model = Brainstorm
	template_name = "threads/brain_form.html"
	#fields = ['topic', 'text', 'owner']
	success_url = reverse_lazy('threads:all_posts')
	print_queries()

	def get(self, request, pk=None):
		form = BrainForm()
		ctx = {'form': form}
		return render(request, self.template_name, ctx)

	def post(self, request, pk=None):
		form = BrainForm(request.POST) 
		brain = form.save(commit=False)
		brain.owner = self.request.user
		brain.save()
		print_queries()
		return redirect(self.success_url)

class BrainRespCreateView(View):
	model = BrainstormResponse
	def post(self, request, pk) :
		b = get_object_or_404(Brainstorm, id=pk)
		owner = self.request.user
		resp = BrainstormResponse(text=request.POST['text'], owner=owner, brainstorm=b)
		resp.save()
		print_queries()
		print(pk.id)
		return redirect(reverse('threads:brainstorm_detail', args=[pk]))

class BrainCommentCreateView(View): # FIX THIS - maybe
	model = BrainstormComment
	def post(self, request, pk) :
		b = get_object_or_404(BrainstormResponse, id=pk)
		owner = self.request.user
		comment = BrainstormComment(text=request.POST['text'], owner=owner, brainstormresponse=b)
		comment.save()
		return redirect(reverse('threads:brainstorm_detail', args=[b.brainstorm.id]))


class AddUpvoteView(View): 
	#model = Vote
	def post(self, request, pk) :
		owner = self.request.user
		print(pk.id)
		br = get_object_or_404(BrainstormResponse, id=pk)
		v = Vote(owner=owner, brainresponse=br)
		try:
			v.save()  # In case of duplicate key
		except IntegrityError as e:
			pass
		#v.save()
		print_queries()
		return redirect(reverse('threads:brainstorm_detail', args=[br.brainstorm.id]))

# class delUpvote(View):

# class upvoteToDownvote(View):

# class addDownvote(View):

# class delDownvote(View):

# class downvoteToUpvote(View)

# ------------------------------------------------------------------------------------

class DiscListView(ListView):
	model = Discussion
	template_name = 'threads/disc_list.html'

discussions/threads/templates/threads/all_posts.html
{% extends "base_menu.html" %}
{% block content %}
<div class="panel panel-default">
<table class="table">
	<tr>
		<th>Topic</th>
		<th>Type</th>
		<th>Author</th>
		<th>Created</th>
	</tr>

{% if all_posts %}
	{% for p in all_posts %}
		{% if p.type == 'reaction' %}
		<tr>
			<td><a href="{% url 'threads:reaction_detail' p.id %}" style="color:{{ p.color }}">{{ p.topic }}</a></td>
			<td><span class='glyphicon glyphicon-share-alt' style='color:lightseagreen'></span></td>

			{% if user == p.owner %}
			<td> </td>
			{% else %}
			<td>{{ p.owner }}</td>
			{% endif %}

			<td>{{ p.created_at }}</td>
		</tr>

		{% elif p.type == 'brainstorm' %}
		<tr>
			<td><a href="{% url 'threads:brainstorm_detail' p.id %}" style="color:{{ p.color }}">{{ p.topic }}</a></td>
			<td><span class='glyphicon glyphicon-check' style='color:mediumpurple'></span></td>

			{% if user == p.owner %}
			<td> </td>
			{% else %}
			<td>{{ p.owner }}</td>
			{% endif %}

			<td>{{ p.created_at }}</td>
		</tr>

		{% else %}
		<tr>
			<td><a href="{% url 'threads:discussion_detail' p.id %}" style="color:{{ p.color }}">{{ p.topic }}</a></td>
			<td><span class='glyphicon glyphicon-comment' style='color:lightcoral'></span></td>
			
			{% if user == p.owner %}
			<td> </td>
			{% else %}
			<td>{{ p.owner }}</td>
			{% endif %}

			<td>{{ p.created_at }}</td>
		</tr>
		{% endif %}
	{% endfor %}
{% endif %}
</table>
</div>
{% endblock %}

discussions/threads/templates/threads/base_menu.html
{% extends "threads/base_bootstrap.html" %}
{% block navbar %}

<nav class="navbar navbar-default navbar-light">
  <div class="container-fluid">
    <div class="navbar-header">
        <a class="navbar-brand" href="/">{{ settings.APP_NAME }}</a>
    </div>
    <!-- https://stackoverflow.com/questions/22047251/django-dynamically-get-view-url-and-check-if-its-the-current-page -->
    <ul class="nav navbar-nav">
      {% url 'threads' as threads %}
      <li {% if request.get_full_path == threads %}class="active"{% endif %}>
          <a href="{% url 'threads:all_posts' %}">All Posts</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
        <li>
        <a href="{% url 'threads:new_post' %}">Create New Post</a>
        </li>
        <li class="dropdown">
            
            <ul class="dropdown-menu">
                <li><a href="{% url 'logout' %}?next={% url 'threads:all_posts' %}">Logout</a></li>
            </ul>
        </li>
        {% else %}
        <li>
        <a href="{% url 'login' %}?next={% url 'threads:all_posts' %}">Login</a>
        </li>
        {% endif %}
    </ul>
  </div>
</nav>
{% endblock %}

discussions/threads/templates/threads/brain_detail.html
{% extends "base_menu.html" %}
{% load crispy_forms_tags %}
{% block content %}

<style>
	.panel-body {
		color:mediumpurple;
	}

	#comments {
		color:#c0a6f5;
	}

	.up {
		background-color:white;
		border-color: lightseagreen;
	}
	#up-votes {
		color:lightseagreen;
	}

	.down {
		background-color:white;
		border-color: lightcoral;
	}
	#down-votes {
		color:lightcoral;
	}

	#vote-label {
		font-family:"Helvetica Neue";
	}

	#commentbutton {
		color:white;
		background-color:#c0a6f5;
		border:none;
		border-radius:4px;
	}
</style>

<div class="panel panel-default">
	<div class="panel-body">
		<h2>{{ brain }}</h2>
		<h3>{{ brain.owner }} : {{ brain.text }}</h3>
		<p>{{ brain.created_at }}</p>
		<div class="btn-group" data-toggle="buttons">
			<label class="btn btn-secondary active">
		    <input type="radio" name="options" id="mostvotes" autocomplete="off" checked> Most Votes
		  </label>
		  <label class="btn btn-secondary">
		    <input type="radio" name="options" id="leastvotes" autocomplete="off" onclick="showLeastVotes()"> Least Votes
		  </label>
		  <label class="btn btn-secondary">
		    <input type="radio" name="options" id="newest" autocomplete="off"> Newest
		  </label>
		  <label class="btn btn-secondary">
		    <input type="radio" name="options" id="oldest" autocomplete="off"> Oldest
		  </label>
		</div>
	</div>
</div>

	{% for b in brain.resps %}
	<div class="panel panel-default" id="mostvotes-list">
		<div class="panel-body">
		<p>{{ b.owner }} : {{ b.text }} (id: {{ b.id }})&nbsp;
		<button type="submit" formmethod="post" class="btn btn-sm up"><a href="{% url 'threads:brainstorm_add_upvote' brain.id %}"><span class="glyphicon glyphicon-thumbs-up" id='up-votes'> <span id='vote-label'>{{ b.up }}</span></span></a></button>

		<button class="btn btn-sm down"><span class="glyphicon glyphicon-thumbs-down" id='down-votes'> <span id='vote-label'>{{ b.down }}</span></span></button></p>
		<p>{{ b.created_at }}</p>
		{% for c in b.r_comments %}
			<p id='comments'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ c.owner }} : {{ c }}</p>
		{% endfor %}
		<button onclick="showCommentForm('{{ b.id }}')">Add Comment</button>
		<form method="post" action="{% url 'threads:brainstorm_comment_create' b.id %}" id='{{ b.id }}' style='display:none'>
			{% csrf_token %}
			{{ comment_form|crispy }}
			<p>&nbsp;&nbsp;&nbsp;&nbsp;<input type="submit" value="Submit"></p>
		</form>
		</div>
	</div>
	{% endfor %}


<div class="panel panel-default">
		<div class="panel-body">
	<p>Respond with a new idea:</p>
	<form method="post" action="{% url 'threads:brainstorm_resp_create' brain.id %}">
		{% csrf_token %}
    	{{ resp_form|crispy }}
		<p><input type="submit" value="Submit new idea"></p>
	</form>
</div>
</div>


<script>
function showCommentForm(formID) {
	var f = document.getElementById(formID);
	if (f.style.display === "none") {
		f.style.display = "block";
	} 	else {
		f.style.display = "none";
	}
}

function showLeastVotes() {
	console.log("is anything working")
	var lvl = document.getElementByID('leastvotes-list');
	lvl.style.display = "block";
	var mvl = document.getElementByID('mostvotes-list');
	mvl.style.display = "none";
}
</script>
{% endblock %}

discussions/threads/templates/threads/brain_list.html
{% extends "threads/base_bootstrap.html" %}
{% block content %}
{% if b_list %}
	{% for b in b_list %}
		<p><a href="{% url 'threads:brainstorm_detail' b.id %}" style="color:mediumpurple">{{ b.text }}</a> by {{ b.owner }}</p>
	{% endfor %}
{% endif %}
<a href="{% url 'threads:brainstorm_create' %}">Create New Brainstorm</a>
{% endblock %}

discussions/threads/templates/threads/disc_list.html
{% extends "threads/base_bootstrap.html" %}
{% block content %}
{% if d_list %}
	{% for d in d_list %}
		<p><a href="{% url 'threads:discussion_detail' d.id %}" style="color:lightcoral">{{ d.topic }}</a> by {{ d.owner }}</p>
	{% endfor %}
{% endif %}
<a href="{% url 'threads:discussion_create' %}">Create New Discussion</a>
{% endblock %}

discussions/threads/templates/threads/new_post.html
{% extends "base_menu.html" %}
{% block content %}
	<h2>Create a new:</h2>
	<div class="container">
		<div class='row'>
			<div class="col-sm-4">
				<a href="{% url 'threads:reaction_create' %}">
				<div class="panel panel-default" style="text-align:center">
					<div class="panel-body" style="color:lightseagreen">
						<span class="glyphicon glyphicon-share-alt" style="color:lightseagreen"></span>&nbsp;&nbsp;Reaction</div>
				</div>
				</a>
			</div>


			<div class="col-sm-4">
				<a href="{% url 'threads:brainstorm_create' %}">
				<div class="panel panel-default" style="text-align:center">
					<div class="panel-body" style="color:mediumpurple">
						<span class="glyphicon glyphicon-check" style="color:mediumpurple"></span>&nbsp;&nbsp;Brainstorm</div>
				</div>
				</a>
			</div>


			<div class="col-sm-4">
				<a href="{% url 'threads:discussion_create' %}">
				<div class="panel panel-default" style="text-align:center">
					<div class="panel-body" style="color:lightcoral">
						<span class="glyphicon glyphicon-comment" style="color:lightcoral"></span>&nbsp;&nbsp;Discussion</div>
				</div>
				</a>
			</div>
		</div>
	</div>
{% endblock %}

discussions/threads/templates/threads/thread_list.html
{% extends "threads/base_bootstrap.html" %}
{% block content %}
{% if r_list %}
	{% for r in r_list %}
		<p><a href="{% url 'threads:reaction_detail' r.id %}" style="color:lightseagreen">{{ r.text }}</a> by {{ r.owner }}</p>
	{% endfor %}
{% endif %}
<a href="{% url 'threads:reaction_create' %}">Create New Reaction</a>
{% endblock %}